stages:
  - lint
cache:
  key:
    files:
      - composer.lock
  paths:
    - vendor/

psr12_check:
  stage: lint
  image: php:8.3.6-cli
  before_script:
    - apt-get update && apt-get install -y unzip git libzip-dev
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified' . PHP_EOL; } else { echo 'Installer corrupt' . PHP_EOL; unlink('composer-setup.php'); exit(1); }"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install 
  script:
    - vendor/bin/phpcs -n --standard=PSR12 src/
  rules:
    - if: $CI_COMMIT_BRANCH